includes = ["**/*.dfy", "../target/cs/src/**/*.cs"]
excludes = ["**/flycheck_*", "../target/**/flycheck_*"]

[options]
type-system-refresh = true
general-traits = "datatype"
general-newtypes = true
standard-libraries = true